### ISSUE TITLE
metadata compatibility question

### ISSUE THREAD

**Issue by danv61** [biosimulators/Biosimulators#543]
Hi @jonrkarr , is the metadata inside the attached omex file compatible with your reader?
It's a small proof of concept file, just to catch early any issue.
I tested it and it passes the validation test at the W3C rdf validator.
Note that this panel doesn't accept omex archives, so I had to change the extension to zip
Thanks!
[biomodel_100596964.zip](https://github.com/biosimulators/Biosimulators/files/8092141/biomodel_100596964.zip)

**Comment by jonrkarr** [comment]
A few things need to be changed:

- The title should use `http://dublincore.org/specifications/dublin-core/dcmi-terms/title` rather than `http://purl.org/dc/elements/1.1/title`. 
  - [ ] Replace
    ```xml
    <dc:title rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Regulation of quantal currents determines synaptic strength at neuromuscular synapses in larval Drosophila</dc:title>
    ```
    with
    ```xml
    <dcterms:title rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Regulation of quantal currents determines synaptic strength at neuromuscular synapses in larval Drosophila</dc:title>
    ```
  - [ ] Replace `http://purl.org/dc/terms/` with `http://dublincore.org/specifications/dublin-core/dcmi-terms/`
- The objects of `http://example.org/contributor0`, `http://example.org/contributor1`, etc. should be instances of `rdf:Description`. 
  - [ ] E.g., replace
    ```xml
    <dc:contributor rdf:about="http://example.org/contributor0">
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Dan Vasilescu</rdfs:label>
        <foaf:name rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Dan Vasilescu</foaf:name>
    </dc:contributor>
    ```
    with
    ```xml
    <rdf:Description rdf:about="http://example.org/contributor0">
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Dan Vasilescu</rdfs:label>
        <foaf:name rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Dan Vasilescu</foaf:name>
    </rdf:Description>
    ```
- The unused namespaces (e.g., `collex`, `sbo`, etc.) can be declared, but this isn't necessary
- I've often seed local resources (e.g., `http://example.org/contributor0`) assigned URIs that are more clearly local such as `local:0`. This clarifies that they aren't expected to be globally meaningful.

**Comment by jonrkarr** [comment]
The validation can be checked at https://run.biosimulations.org/utils/validate-project
